### ISSUE TITLE
Unable to download your finetuned Bert model

### ISSUE THREAD

**Issue by Saumajit** [monologg/GoEmotions-pytorch#1]
Please provide the aws link for downloading your finetuned model. Thanks.

**Comment by monologg** [comment]
https://huggingface.co/monologg/bert-base-cased-goemotions-ekman
https://huggingface.co/monologg/bert-base-cased-goemotions-group
https://huggingface.co/monologg/bert-base-cased-goemotions-original

Please see `List all files in model` in pages above.

**Comment by Saumajit** [comment]
I tried to download all the files and use it for prediction as shown in your github readme. It is showing me 
UnicodeDecodeError : 'utf-8' codec can't decode byte : invalid continuation byte. Please let me know how to fix this.

**Comment by monologg** [comment]
> I tried to download all the files and use it for prediction as shown in your github readme. It is showing me
> UnicodeDecodeError : 'utf-8' codec can't decode byte : invalid continuation byte. Please let me know how to fix this.

First of all, **you don't have to download the files manually**. If you run the code below, **all the files will be downloaded automatically from huggingface s3**

```python
from transformers import BertTokenizer
from model import BertForMultiLabelClassification
from multilabel_pipeline import MultiLabelPipeline
from pprint import pprint

tokenizer = BertTokenizer.from_pretrained("monologg/bert-base-cased-goemotions-original")
model = BertForMultiLabelClassification.from_pretrained("monologg/bert-base-cased-goemotions-original")

goemotions = MultiLabelPipeline(
    model=model,
    tokenizer=tokenizer,
    threshold=0.3
)

texts = [
    "Hey that's a thought! Maybe we need [NAME] to be the celebrity vaccine endorsement!",
    "it’s happened before?! love my hometown of beautiful new ken 😂😂",
    "I love you, brother.",
    "Troll, bro. They know they're saying stupid shit. The motherfucker does nothing but stink up libertarian subs talking shit",
]

pprint(goemotions(texts))
```

Plz run this code and **write all the logs** you got:)

**Comment by Saumajit** [comment]
I ran this snippet of code and got the mentioned error. I have to download
it manually as my http access is blocked. So it can't be downloaded while
running the code. Please give me some idea if possible why the earlier
mentioned error is happening.

**Comment by monologg** [comment]
I can't infer the reason only based on the one line of the log that you gave. (`UnicodeDecodeError : 'utf-8' codec can't decode byte : invalid continuation byte`) 

**You should give all the log from console.**

What I can only guess is that **you might not save the file (`vocab.txt` etc) in utf-8 format**.

Can you check the encoding of the files?
